# auto-generated by icc_crystallize — review before promoting
# intent_signature: mock.read.state
# synthesized_at: 1775472236

def run_read(metadata, args):
    __args = args  # compat with exec __args scope
    # --- CRYSTALLIZED ---
    __result = [{'v': 1}]
    # --- END ---
    return __result  # exec code must set __result = [{...}]


def verify_read(metadata, args, rows):
    return {"ok": bool(rows)}
