"""Backward-compatibility shim — real code lives in scripts/admin/runner.py."""
from scripts.admin.runner import (
    _local_plugin_version,
    _load_runner_config,
    _save_runner_config,
    _run_checked,
    _remote_root_expr,
    _remote_root_expr_win,
    _read_remote_plugin_version,
    _probe_runner_health,
    cmd_runner_status,
    cmd_runner_config_status,
    cmd_runner_config_set,
    cmd_runner_config_unset,
    cmd_runner_deploy,
    cmd_runner_bootstrap,
    render_runner_status_pretty,
)

__all__ = [
    "_local_plugin_version",
    "_load_runner_config",
    "_save_runner_config",
    "_run_checked",
    "_remote_root_expr",
    "_remote_root_expr_win",
    "_read_remote_plugin_version",
    "_probe_runner_health",
    "cmd_runner_status",
    "cmd_runner_config_status",
    "cmd_runner_config_set",
    "cmd_runner_config_unset",
    "cmd_runner_deploy",
    "cmd_runner_bootstrap",
    "render_runner_status_pretty",
]
