# auto-generated by icc_crystallize — review before promoting
# intent_signature: zwcad.write.add-wall
# synthesized_at: 1775516406

def run_write(metadata, args):
    __args = args  # compat with exec __args scope
    # --- CRYSTALLIZED ---
    v = 1
    # --- END ---
    return __action  # exec code must set __action = {"ok": True, ...}


def verify_write(metadata, args, action_result):
    return {"ok": bool(action_result.get("ok"))}
