# auto-generated by icc_crystallize — review before promoting
# intent_signature: zwcad.write.window-rate-test
# synthesized_at: 1776435690

def run_write(metadata, args):
    __args = args  # compat with exec __args scope
    # --- CRYSTALLIZED ---
    x = 1
    # --- END ---
    return locals().get('__action', {"ok": True})  # exec code sets __action; fallback avoids NameError on auto-activate


def verify_write(metadata, args, action_result):
    return {"ok": bool(action_result.get("ok"))}
