# auto-generated by icc_crystallize — review before promoting
# intent_signature: test.read.synth
# synthesized_at: 1775516406

def run_read(metadata, args):
    __args = args  # compat with exec __args scope
    # --- CRYSTALLIZED ---
    __result = [{'i': 18}]
    # --- END ---
    return __result  # exec code must set __result = [{...}]


def verify_read(metadata, args, rows):
    return {"ok": bool(rows)}
