# auto-generated by icc_crystallize — review before promoting
# intent_signature: cloud-server.write.apply-test
# synthesized_at: 1776420349

def run_write(metadata, args):
    __args = args  # compat with exec __args scope
    # --- CRYSTALLIZED ---
    result = 42
    # --- END ---
    out = dict(locals().get('__action', {"ok": True}))
    if "scenario" in args:
        out["scenario"] = args["scenario"]
    return out


def verify_write(metadata, args, action_result):
    return {"ok": bool(action_result.get("ok"))}
