# auto-generated by icc_crystallize — review before promoting
# intent_signature: cloud-server.write.apply-test
# synthesized_at: 1776420349
from pathlib import Path

import yaml  # type: ignore

from scripts.pipeline_yaml_engine import YAMLScenarioEngine


def run_write(metadata, args):
    scenario_name = str(args.get("scenario", "")).strip()
    if not scenario_name:
        return {"ok": False, "error": "missing 'scenario' arg"}
    scenarios_dir = Path(__file__).parent / "scenarios"
    scenario_path = scenarios_dir / f"{scenario_name}.yaml"
    if not scenario_path.exists():
        return {"ok": False, "error": f"scenario not found: {scenario_name}"}
    scenario_data = yaml.safe_load(scenario_path.read_text(encoding="utf-8"))
    engine = YAMLScenarioEngine()
    result = engine.execute(scenario_data, args, mode="write")
    action = result.get("action_result", {})
    action["scenario"] = scenario_name
    action.setdefault("ok", True)
    return action


def verify_write(metadata, args, action_result):
    return {"ok": bool(action_result.get("ok"))}
